### ISSUE TITLE
IncompressibleFlow deprecated in Phiflow >=2

### ISSUE THREAD

**Issue by akrzgc** [tum-pbs/Solver-in-the-Loop#1]
Hello,

There is a dependency on IncompressibleFlow class which is deprecated in Phiflow >=2.
Latest version supporting IncompressibleFlow is phoflow==1.5.1

Maybe it is worth to mention it in the README :)

Best Regards,
Adam

**Comment by thunil** [comment]
Thanks for pointing this out! It's clarified now in the 'Requirements' section, and the phi2 branch is experimental but worth checking out. This notebook https://www.physicsbaseddeeplearning.org/diffphys-code-sol.html also runs the karman case with phiflow 2.
