### ISSUE TITLE
Is the circular obstacle position in generated hires data is different than readme/paper figures?

### ISSUE THREAD

**Issue by chrundle** [tum-pbs/Solver-in-the-Loop#2]
I hope you are doing well today. I used the following instructions in the readme to generate the hi-resolution data:
```
make karman-fdt-hires-set      # Generate traning data set
make karman-fdt-hires-testset  # Generate test data set
```
The position of the circular obstacle in the data generated where I used your code appears to be at the position (1/2, 1/2) in the domain [0,1]x[0,2] as described in section B.1 of your Solver in the Loop paper. Here is a sample from the generated data below:
<img width="143" alt="karman-2d-hires-sample" src="https://user-images.githubusercontent.com/23193073/163612599-8e753593-b457-4795-82d1-a87a7cda72a5.png">
This differs from the images presented in the readme and paper in which the the circular obstacle is at the bottom of the domain. 

Are the simulation images provided in the readme/paper cropped or did I somehow generate data that is different from what is being used to get your results in the paper? 

Another reason I ask is because I computed the low-resolution simulation data then computed the average of the MAE for the 5 test simulations (i.e. $(1/5) sum_{i=1}^5 MAE(lo_res_sim_i, hi_res_sim_i)$) and got 0.178. However, Table 1 in your paper seems to indicate this value should be 0.146. 

Any thoughts or insight on this would be appreciated. Thank you!

**Comment by thunil** [comment]
The obstacle is definitely centered in the half of the domain towards the inflow. The MAE differences potentially come from differences in the test cases, I can recommend to primarily look at improvements of the learned models relative to this MAE baseline.
